X_RAPIDAPI_HOST = "api-football-v1.p.rapidapi.com"
X_RAPIDAPI_IMG_SEARCH_HOST = "bing-image-search1.p.rapidapi.com"
X_RAPIDAPI_VIDEO_SEARCH_HOST = "free-football-soccer-videos.p.rapidapi.com"
X_YOUTUBE_SEARCH_HOST = "youtube-search3.p.rapidapi.com"
X_WORLDOMETERS_HOST = "worldometers.p.rapidapi.com"
X_RAPIDAPI_KEY = "your-rapidapi-key"
